spring:
  application:
    name: BrzFinances-test
  datasource:
    url: jdbc:h2:mem:testdb
    password:
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      show-sql: true
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console