spring:
  application:
    name: BrzFinance
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/brz_finances
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: create-drop
  profiles:
    active:
